### ISSUE TITLE
Telephone does not use the default audio input/output device

### ISSUE THREAD

**Issue by jbehr** [eofster/Telephone#100]
I use different audio devices for input/output (e.g. iphone headset with cable, bluetouth bluetooth headphones, ...) and most programs (e.g. itunes, Skype, ...) use always the systemwide selected device. But Telephone always sticks with the "Build-in Microphonne" and "Built-in Output". How can Telephone switch to the same as the system?

![screen shot 2014-02-17 at 14 35 45](https://f.cloud.github.com/assets/557881/2185668/883f2d78-97d9-11e3-9e84-71045703341e.png)

![screen shot 2014-02-17 at 14 35 08](https://f.cloud.github.com/assets/557881/2185660/6599d4b2-97d9-11e3-83af-979e2e2e0fdb.png)

**Comment by eofster** [comment]
I believe that the deeper problem could be that Telephone wasn’t keeping the previously selected audio devices. This is a regression fixed by #143 and should already be available in the released version. See also discussion in #103.

Please also feel free to reopen this issue if the real problem hasn’t been fixed or a specific use case is still not possible.

**Comment by kbrock** [comment]
@eofster thanks for the fix
