### ISSUE TITLE
Re-register after waking from sleep

### ISSUE THREAD

**Issue by eofster** [eofster/Telephone#144]
Currently Telephone relies on OS X network reachability mechanism to re-register accounts after computer wakes from sleep. Although this worked well before, it doesn’t work in the recent OS X versions.

An independent mechanism for re-registering must be introduced. Several attempts to re-register should be made. The intervals between the attempts should increase after each failed attempt. The host reachability change from unreachable to reachable should trigger an out-of-order attempt.

Related issues: #79 #117

**Comment by hexerei** [comment]
Looks like you found the troublemaker. And it sounds convincing, since i have not seen those errors before, until i updated to OS X El Capitan.

So here is my last crash report:
https://gist.github.com/hexerei/be88994770ca009157c9#file-dump

All in all El Capitan runs fast and reliable - only Telephone never woke up from it’s sleep, leaving an imaginary huge pile of dead Telephone threads - they had not seen much in their one-day life. Only sleep seemed comfortable for them, not knowing, that this would be the end.

I really want to get rid of them :-(

**Comment by adamhorner** [comment]
+1 for a fix to this - at the moment I have to keep checking that telephone is still 'Available' whenever I return to my computer. (Great app by the way, I love the minimalism/simplicity)

**Comment by nestsman** [comment]
Just checking to see how soon this bug might be fixed.

Thank you.

**Comment by eofster** [comment]
This one together with #145 are the most important bug fixes that I want to deliver as part of the 1.1.5 release. I’ll start working on this one after I’m done with the follow-ups of #145.

**Comment by eofster** [comment]
Independent mechanism for re-regestring wasn’t introduced, but I think the issue should now be resolved.
