### ISSUE TITLE
DyLD image not found error in archived Telephone 1.1.4 (2016-01-01)

### ISSUE THREAD

**Issue by robertoschwald** [eofster/Telephone#162]
Built Telephone version of today (2016-01-01) in XCode 7.2 with pjproject-2.4.5.
It runs when started within XCode, but as soon as I export the Application as Standalone, I receive:

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Domain.framework/Versions/A/Domain
  Referenced from: /Users/USER/Desktop/*/Telephone.app/Contents/MacOS/Telephone
  Reason: image not found

**Comment by nriley** [comment]
You need to add Domain.framework and UseCases.framework to the Copy Files build phase for the Telephone target (and potentially also add some target dependencies, though it seems like they get built anyway); these aren't getting copied into the bundle.  Once I did this I am able to launch it from the Finder rather than just from Xcode.

**Comment by robertoschwald** [comment]
That should normally be part of the xCode project file setup checked into git, right?

**Comment by nriley** [comment]
Yes, it should be.  Here's a patch:

http://sabi.net/temp/tlphn-copy-files.patch
