### ISSUE TITLE
Crash when opening the Preferences

### ISSUE THREAD

**Issue by stonerl** [eofster/Telephone#221]
I'm using the latest AppStore-Version (1.1.6) on OSX 10.11.4 and everytime I open the Preferences the App crashes.

**Comment by eofster** [comment]
Could you paste or attach the crash log here?

**Comment by stonerl** [comment]
Here is the link to the gist: https://gist.github.com/stonerl/8564cc8516a7db7e31b2e09c96dd6d91.js

It seems Telephone cannot save the Settings. I was able to open the Settings once but there was no Account on the Account-Page. After starting telephone again it showed me the first start screen once again.

Now it seems it has saved the Account but as soon as I click on any tab e.g. Accounts, Sound, Network it crashes.

**Comment by stonerl** [comment]
Now it also crashes when I try to make a call...

**Comment by stonerl** [comment]
I stumbled across this app:
https://itunes.apple.com/de/app/phone.systems-softphone/id642055429?l=en&mt=12
which seems to be your app just relabeled. This one works for me. I just noticed that Telephone does not ask for Keychain Access while the other one does. Could this be the problem?

**Comment by eofster** [comment]
This app is an outdated Telephone’s clone.

It is normal that the OS doesn’t show the Keychain Access dialog. If the app creates an entry in the Keychain, it later has access to that entry. The dialog is shown when _another_ app tries to access the same entry. Because the app you mentioned is a clone, it tries to access the same entries and you see the dialog.

The crash happens in the new code that enumerates and maps system audio devices to the audio devices used in the SIP library. I see it happening to some users but so far I couldn’t find out the reason.

Do you have any audio devices connected to your computer? Maybe Bluetooth audio?

**Comment by stonerl** [comment]
I'm using the Ultraschall-Hub for Podcasting. http://ultraschall.fm/install/

This adds several audio devices (see the screenshot). The Aggregated Device also contains microphone that is currently not connected.

![screen shot 2016-04-23 at 04 19 38](https://cloud.githubusercontent.com/assets/2091312/14752537/c15dde7a-090a-11e6-857a-64f99d786c4c.png)

**Comment by stonerl** [comment]
It was the inactive "Yeti Sterio Microphone" you can see in the screenshot. When the device is not connect Telephone crashes. As soon as I plug the Microphone in Telephony does not crash anymore

**Comment by eofster** [comment]
How can I open the same window? I installed Ultraschall-Hub, but no app seems to be installed.

**Comment by stonerl** [comment]
OSX has an Application called Audio MIDI Setup.

**Comment by eofster** [comment]
Is it possible to reproduce this state without a real microphone?

**Comment by stonerl** [comment]
I don't think so. Because the crash always happened when the USB-Microphone was part of the Aggregated Device but not plugged in. Plugin it in or removing it from the Aggregated Device stopped Telephone from crashing. But I don't know how to reproduce this without a physical device.
