### ISSUE TITLE
'Call back' button times-out

### ISSUE THREAD

**Issue by benrubson** [eofster/Telephone#236]
Hello,

As I explained in #98, when used SIP port is not the default one (you use mysipprov.net:1234 in `domain` field), 'call back' button times-out.
This bug is still here in 1.1.7.

Thank you !

Ben

**Comment by benrubson** [comment]
To give additional details :
- 'call back' button **works** for windows which initially **placed** the call.
- 'call back' button **does not work** for windows which initially **received** the call.

**Comment by eofster** [comment]
Does it work if you configure proxy for this account in the advanced account settings? For your example that would be:
```
[x] Connect using proxy
Server: mysipprov.net
Port: 1234
```

**Comment by benrubson** [comment]
Yes, adding proxy info makes the 'call back' button work.
Nice workaround 👍 
Does it help you finding the bug ?

**Comment by eofster** [comment]
Not sure yet. It may be a bug, but may be not. I’ll provide more info when I get to this issue.

**Comment by eofster** [comment]
This is actually by design. An incoming call has a logical address like `user@company.com` and a connection address, which contains an IP and host for the communication like `user@1.2.3.4:1234`. The connection address can be expected to be valid in the near future, but not indefinitely. You may want to call back in several hours, when the IP address and port of the remote party has already been changed. It’s their server who knows the exact IP address and port of the remote party’s phone. And the normal calling and route finding rules (call a logical address `user@company.com`) should be used for calling back.

The Domain field in Telephone’s UI acts like a shortcut. First it is used to compose your logical address that will be used for outgoing calls (and for calling you back). Second, by default it is used as a registry server address, which can be changed in the advanced account settings. So normally you would want to keep your logical address without the networking details like a port number, but you just want to be able to tell Telephone, “please make all requests via this host and this port.” And that’s exactly what SIP Proxy is for.

So if there is a problem, it is in how Telephone’s UI allows or doesn’t allow the user to fill out the correct fields, but not in the underlying data handling logic.

**Comment by benrubson** [comment]
Understood, thank you for your clarification Alexey 👍 
It's now clear how fields should be used, and why.
Perfect !
