### ISSUE TITLE
Audio Quality Problem

### ISSUE THREAD

**Issue by lukaseppler** [eofster/Telephone#31]
In many calls I get the other party complaining that the audio is jittered. I can hear them well. Since Telephone has little configuration (which I like) I don't know where to start looking (which I like less). My SIP provider tells me to use uLaw (G711a) for transport, which I can't verify.

Where can I start?

**Comment by rmm5t** [comment]
I still get complaints from the other party about voice quality issues. I don't have this issue with anything else on the same network. I even have a Polycom phone that I've tried with great quality. There's something wrong with Telephone.app here.

**Comment by eofster** [comment]
Voice quality is a complex problem. I suspect that this issue has gathered several independent cases of the problem. I would start with checking the “Use only G.711 codec” checkbox in Telephone’s Sound preferences. This should help in case of using FritzBox (because it has G.722 codec incompatibility) and in case when the provider explicitly asks to use G.711 codec.

**Comment by eofster** [comment]
I believe that audio quality problems are not generic but rather specific to a particular case. If you still have them and wish them to be fixed, please write to the [support address](http://www.64characters.com/support/) to discuss them in more details.
